version: 2.1
orbs:
  node: circleci/node@4.7.0
  go: circleci/go@1.7.0

jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/install
      - run: npm install
      - run: npm run dev
      - run: pwd ; ls -R ; cd ; ls -R
