name: Spindly Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: APT update
      run: sudo apt-get update
    
    - name: Install packs
      run: sudo apt-get install -y libwebkit2gtk-4.0-dev

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      with:
        # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version
        node-version-file: .nvmrc
        
    - name: NPM Run build
      run: npm run build
        
    - name: Upload Build Artifact Linux
      uses: actions/upload-artifact@v2.3.1
      with:
        name: LinuxBuild
        path: published-app
        if-no-files-found: error
        retention-days: 90

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      with:
        # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version
        node-version-file: .nvmrc
        
    - name: NPM Run build
      run: npm run build
        
    - name: Upload Build Artifact Linux
      uses: actions/upload-artifact@v2.3.1
      with:
        name: WindowsBuild
        path: published-app
        if-no-files-found: error
        retention-days: 90
